# Generated by Django 4.2.1 on 2023-06-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=100)),
                ('description', models.TextField(default='description')),
                ('year', models.CharField(default='2023', max_length=4)),
                ('semester', models.CharField(default='spring', max_length=10)),
                ('lecture', models.CharField(default='lecture', max_length=100)),
                ('instructor', models.CharField(default='instructor', max_length=100)),
                ('thumbnail', models.FileField(upload_to='')),
                ('play_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('video_file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'videos',
            },
        ),
    ]
