# Generated by Django 4.2.1 on 2023-06-09 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=100)),
                ('description', models.TextField(default='description')),
                ('year', models.CharField(default='2023', max_length=4)),
                ('semester', models.CharField(default='spring', max_length=10)),
                ('lecture', models.CharField(default='lecture', max_length=100)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'lectures',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='video title', max_length=100)),
                ('description', models.TextField(default='video description')),
                ('thumbnail', models.FileField(blank=True, upload_to='')),
                ('play_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='uploader.lecture')),
            ],
            options={
                'verbose_name_plural': 'videos',
            },
        ),
    ]
