# Generated by Django 4.2.1 on 2023-05-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="video",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="play_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
