# Generated by Django 4.2.1 on 2023-05-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "uploader",
            "0002_video_description_video_like_count_video_play_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="lecture",
            field=models.CharField(default="lecture", max_length=100),
        ),
        migrations.AddField(
            model_name="video",
            name="semester",
            field=models.CharField(default="spring", max_length=10),
        ),
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.FileField(default="default", upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="year",
            field=models.CharField(default="2023", max_length=4),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(default="description"),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(default="title", max_length=100),
        ),
    ]
