# Generated by Django 4.2.1 on 2023-06-05 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=100)),
                ('description', models.TextField(default='description')),
                ('instructor', models.CharField(default='instructor', max_length=100)),
                ('year', models.CharField(default='2023', max_length=4)),
                ('semester', models.CharField(default='spring', max_length=10)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'lectures',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=100)),
                ('description', models.TextField(default='description')),
                ('year', models.CharField(default='2023', max_length=4)),
                ('semester', models.CharField(default='spring', max_length=10)),
                ('lecture', models.CharField(default='lecture', max_length=100)),
                ('instructor', models.CharField(default='instructor', max_length=100)),
                ('thumbnail', models.FileField(upload_to='')),
                ('play_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('video_file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'videos',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(default='student', max_length=20)),
                ('nickname', models.CharField(max_length=50)),
                ('validation_code', models.CharField(max_length=30, null=True)),
                ('jwt_token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elearning.jwttoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
