# Generated by Django 4.2.1 on 2023-06-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(default='lecture_description'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(default='lecture_title', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(default='video_description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='video_title', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
