# Generated by Django 4.2.1 on 2023-05-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='email',
            new_name='user_id',
        ),
    ]
