# Generated by Django 4.2.1 on 2023-05-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_remove_userinfo_user_id_userinfo_user_jwttoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='validation_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
