# Generated by Django 4.2.1 on 2023-05-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_userinfo_validation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwttoken',
            name='token',
            field=models.BinaryField(max_length=255, unique=True),
        ),
    ]
