# Generated by Django 4.2.1 on 2023-06-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_alter_jwttoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_role',
            field=models.CharField(default='student', max_length=10),
        ),
    ]
