# Generated by Django 4.2.1 on 2023-06-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_userinfo_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profile_image',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='subscribe_num',
            field=models.IntegerField(default=0),
        ),
    ]
