# Generated by Django 4.2.1 on 2023-06-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_userinfo_profile_image_userinfo_subscribe_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_image',
            field=models.CharField(default='default_profile.png', max_length=50),
        ),
    ]
